# Generated by Django 5.0.6 on 2024-06-11 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('defeated_player', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('surface', models.CharField(max_length=50)),
                ('round', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=50)),
                ('result', models.BooleanField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='dashboard.player')),
            ],
        ),
    ]
