# Generated by Django 5.0.6 on 2024-06-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='opponent_rank',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='result',
            field=models.CharField(max_length=20),
        ),
    ]
