# Generated by Django 5.0.6 on 2024-06-19 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=10)),
                ('hand', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('wins_semester', models.CharField(max_length=10)),
                ('losses_semester', models.CharField(max_length=10)),
                ('wins_year', models.CharField(max_length=10)),
                ('losses_year', models.CharField(max_length=10)),
                ('wins_clay', models.CharField(max_length=10)),
                ('losses_clay', models.CharField(max_length=10)),
                ('wins_hard', models.CharField(max_length=10)),
                ('losses_hard', models.CharField(max_length=10)),
                ('wins_grass', models.CharField(max_length=10)),
                ('losses_grass', models.CharField(max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='dashboard.player')),
            ],
        ),
    ]
