# Generated by Django 5.0.6 on 2024-06-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_playerstats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerStats',
            new_name='PlayerStat',
        ),
    ]
