# Generated by Django 5.0.6 on 2024-06-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_playerstats_playerstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.CharField(max_length=100)),
                ('surface', models.CharField(max_length=10)),
            ],
        ),
    ]
